Polaris update (#23)
* Update pipeline (#22)

* Added support fir build-args for container-ci workflow

* Added default build-args logic, and renamed the build-args input parameter ti extra-build-args

* Added custom user-defined tags support

* Added support for ignoring hadolint rules

* Added missing git metadata step

* Modified author injection for commit vars

* Added debug step for commit author

* Added missing git fetch info

* Updated git tech depth

* Updated fetch depth

* Fixed steps order in docker image build step

* Fixed formatting issues with args

* Refactored arg parse for docker build

* Rationalized build args steps

* Added missing checkout step

* Trimmed arg-json command

* Updated args json for build-args phase

* Updated build-args logic

* Updated build-args logic

* Updated and refactored :
- Added support for Dockles Ignore
- Added support for Trivy Ignores
- Optimized workflow by removing duplicated steps qs much as possible whilst keeping parallelization
- Renamed a few steps for clarity

* Updated defaults for a few params

* Fixed weog version definition and updated parameters

* Refactored an bu,ped hadolint action version

* Added skip trivy init where it as needed

* Fixed wrong dockle parameter for scan

* Updated README

* Made artifacts refere,ce unique

* Updated docs

* Cheese dockle by running it from binary

* Clean dockle step and add argument handleling

* Fix tentative when building chart depedencies -> ignoring oci repositories

* Added fix at frst step too

* Added back missing chart dir as param

* Doc update : calling workflows

* Change release suffix condition for dev branch

* Change condition for running chart-releaser on branches

* Add release steps for feature branch in CI workflow

* add skip

* Comment on repository OCI definition

* fix CI

* Clarify release types and update workflow references

Updated README to clarify release management and workflow usage.

* update rules

* Fix config on CI Linter

* fix Yaml Linter error

* Fix Linter Errors

* Fix :

Error: ub/workflows/ci.yml:11:16: [error] too many spaces inside brackets (brackets)
Error: ub/workflows/ci.yml:11:24: [error] too few spaces after comma (commas)
Error: ub/workflows/ci.yml:11:29: [error] too many spaces inside brackets (brackets)

* add exclusion OCI helm repository

* refactoring + set path

* rebuild DEV / SNAPSHOT every time called

* fix chart release that not update index.yaml

* fix yaml lint errors

* refactor

* update version of tools used by the workflow

* add checkout

* set the version of helm (same in all steps)

* Log more info for the name of the version

* Update config for chart-Releaser

* skip upload if it is already made

* remove download

* try without upload / download at each job the chart

* Need source  for Polaris Scan

* Delete release before create it again

* skip if existe

* from main

* new line at end of file

* test option with index

* add feature branch in release process

* Choose the right package-path

* fix linter error : Error: ub/workflows/chart-ci.yml:361:1: [error] too many blank lines (1 > 0) (empty-lines)

* remove CR releaser

* downgrade chart-releaser plugin

* remove download chart

* [Temporary] Disable Helm, Checkout, Downloard pakaged Chart

* Add Chechout step

* Add Helm

* All do in 1 job

* Adjust task order in the job

* Replace chart-releaser by specifics steps.

* uncomment the right step for snapshot version name

* remove tag creation

* add login for fetch gh-pages

* Clean before MR

* add merge with helm before cr index

* update url in index.yaml

* update index with cr_releaser 1.7.0

* Fix for "chart-cr" action bug https://github.com/helm/chart-releaser-action/issues/171#issuecomment-2372464055

* same error

* Put latest tag at the right step

* again : latest_tag

* Latest tag

* Latest

* Latest tag from $tag

* Latest

* export latest

* CR and GH

* Prepare git for chart-releaser

* Latest

* CR update

* do it by cr

* Fix version in chart.

* Update CR rags + upload release

* remove upload in case : immutable release

* Cr args : owner and repo

* Remove unused instructions

* Add git login

* remove OCI in dependancies list

* Remove Hardcode

* lower ?

* name use for tag and for CR

* Name

* Name

* Name

* Name

* Name

* Name

* looking for folder structure load for gh-pages branch

* Name

* Name .

* Ref the commit that run the workflow

* Add changelog.md as ref to release

* Update trivy action to 0.35.0 (#15)

* Update trivy (#19)

* Fix release on Immutable TAG / RELEASE - Yaml Linter (#12)

* Added support fir build-args for container-ci workflow

* Added default build-args logic, and renamed the build-args input parameter ti extra-build-args

* Added custom user-defined tags support

* Added support for ignoring hadolint rules

* Added missing git metadata step

* Modified author injection for commit vars

* Added debug step for commit author

* Added missing git fetch info

* Updated git tech depth

* Updated fetch depth

* Fixed steps order in docker image build step

* Fixed formatting issues with args

* Refactored arg parse for docker build

* Rationalized build args steps

* Added missing checkout step

* Trimmed arg-json command

* Updated args json for build-args phase

* Updated build-args logic

* Updated build-args logic

* Updated and refactored :
- Added support for Dockles Ignore
- Added support for Trivy Ignores
- Optimized workflow by removing duplicated steps qs much as possible whilst keeping parallelization
- Renamed a few steps for clarity

* Updated defaults for a few params

* Fixed weog version definition and updated parameters

* Refactored an bu,ped hadolint action version

* Added skip trivy init where it as needed

* Fixed wrong dockle parameter for scan

* Updated README

* Made artifacts refere,ce unique

* Updated docs

* Cheese dockle by running it from binary

* Clean dockle step and add argument handleling

* Fix tentative when building chart depedencies -> ignoring oci repositories

* Added fix at frst step too

* Added back missing chart dir as param

* Doc update : calling workflows

* Change release suffix condition for dev branch

* Change condition for running chart-releaser on branches

* Add release steps for feature branch in CI workflow

* add skip

* Comment on repository OCI definition

* fix CI

* Clarify release types and update workflow references

Updated README to clarify release management and workflow usage.

* update rules

* Fix config on CI Linter

* fix Yaml Linter error

* Fix Linter Errors

* Fix :

Error: ub/workflows/ci.yml:11:16: [error] too many spaces inside brackets (brackets)
Error: ub/workflows/ci.yml:11:24: [error] too few spaces after comma (commas)
Error: ub/workflows/ci.yml:11:29: [error] too many spaces inside brackets (brackets)

* add exclusion OCI helm repository

* refactoring + set path

* rebuild DEV / SNAPSHOT every time called

* fix chart release that not update index.yaml

* fix yaml lint errors

* refactor

* update version of tools used by the workflow

* add checkout

* set the version of helm (same in all steps)

* Log more info for the name of the version

* Update config for chart-Releaser

* skip upload if it is already made

* remove download

* try without upload / download at each job the chart

* Need source  for Polaris Scan

* Delete release before create it again

* skip if existe

* from main

* new line at end of file

* test option with index

* add feature branch in release process

* Choose the right package-path

* fix linter error : Error: ub/workflows/chart-ci.yml:361:1: [error] too many blank lines (1 > 0) (empty-lines)

* remove CR releaser

* downgrade chart-releaser plugin

* remove download chart

* [Temporary] Disable Helm, Checkout, Downloard pakaged Chart

* Add Chechout step

* Add Helm

* All do in 1 job

* Adjust task order in the job

* Replace chart-releaser by specifics steps.

* uncomment the right step for snapshot version name

* remove tag creation

* add login for fetch gh-pages

* Clean before MR

* add merge with helm before cr index

* update url in index.yaml

* update index with cr_releaser 1.7.0

* Fix for "chart-cr" action bug https://github.com/helm/chart-releaser-action/issues/171#issuecomment-2372464055

* same error

* Put latest tag at the right step

* again : latest_tag

* Latest tag

* Latest

* Latest tag from $tag

* Latest

* export latest

* CR and GH

* Prepare git for chart-releaser

* Latest

* CR update

* do it by cr

* Fix version in chart.

* Update CR rags + upload release

* remove upload in case : immutable release

* Cr args : owner and repo

* Remove unused instructions

* Add git login

* remove OCI in dependancies list

* Remove Hardcode

* lower ?

* name use for tag and for CR

* Name

* Name

* Name

* Name

* Name

* Name

* looking for folder structure load for gh-pages branch

* Name

* Name .

* Ref the commit that run the workflow

* Add changelog.md as ref to release

---------

Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>
Co-authored-by: Lajus <cedric.lajus@aphp.fr>
Co-authored-by: Cédric Lajus <74196307+Superfluxx@users.noreply.github.com>

* trivy (#16)

* Added support fir build-args for container-ci workflow

* Added default build-args logic, and renamed the build-args input parameter ti extra-build-args

* Added custom user-defined tags support

* Added support for ignoring hadolint rules

* Added missing git metadata step

* Modified author injection for commit vars

* Added debug step for commit author

* Added missing git fetch info

* Updated git tech depth

* Updated fetch depth

* Fixed steps order in docker image build step

* Fixed formatting issues with args

* Refactored arg parse for docker build

* Rationalized build args steps

* Added missing checkout step

* Trimmed arg-json command

* Updated args json for build-args phase

* Updated build-args logic

* Updated build-args logic

* Updated and refactored :
- Added support for Dockles Ignore
- Added support for Trivy Ignores
- Optimized workflow by removing duplicated steps qs much as possible whilst keeping parallelization
- Renamed a few steps for clarity

* Updated defaults for a few params

* Fixed weog version definition and updated parameters

* Refactored an bu,ped hadolint action version

* Added skip trivy init where it as needed

* Fixed wrong dockle parameter for scan

* Updated README

* Made artifacts refere,ce unique

* Updated docs

* Cheese dockle by running it from binary

* Clean dockle step and add argument handleling

* Fix tentative when building chart depedencies -> ignoring oci repositories

* Added fix at frst step too

* Added back missing chart dir as param

* Doc update : calling workflows

* Change release suffix condition for dev branch

* Change condition for running chart-releaser on branches

* Add release steps for feature branch in CI workflow

* add skip

* Comment on repository OCI definition

* fix CI

* Clarify release types and update workflow references

Updated README to clarify release management and workflow usage.

* update rules

* Fix config on CI Linter

* fix Yaml Linter error

* Fix Linter Errors

* Fix :

Error: ub/workflows/ci.yml:11:16: [error] too many spaces inside brackets (brackets)
Error: ub/workflows/ci.yml:11:24: [error] too few spaces after comma (commas)
Error: ub/workflows/ci.yml:11:29: [error] too many spaces inside brackets (brackets)

* add exclusion OCI helm repository

* refactoring + set path

* rebuild DEV / SNAPSHOT every time called

* fix chart release that not update index.yaml

* fix yaml lint errors

* refactor

* update version of tools used by the workflow

* add checkout

* set the version of helm (same in all steps)

* Log more info for the name of the version

* Update config for chart-Releaser

* skip upload if it is already made

* remove download

* try without upload / download at each job the chart

* Need source  for Polaris Scan

* Delete release before create it again

* skip if existe

* from main

* new line at end of file

* test option with index

* add feature branch in release process

* Choose the right package-path

* fix linter error : Error: ub/workflows/chart-ci.yml:361:1: [error] too many blank lines (1 > 0) (empty-lines)

* remove CR releaser

* downgrade chart-releaser plugin

* remove download chart

* [Temporary] Disable Helm, Checkout, Downloard pakaged Chart

* Add Chechout step

* Add Helm

* All do in 1 job

* Adjust task order in the job

* Replace chart-releaser by specifics steps.

* uncomment the right step for snapshot version name

* remove tag creation

* add login for fetch gh-pages

* Clean before MR

* add merge with helm before cr index

* update url in index.yaml

* update index with cr_releaser 1.7.0

* Fix for "chart-cr" action bug https://github.com/helm/chart-releaser-action/issues/171#issuecomment-2372464055

* same error

* Put latest tag at the right step

* again : latest_tag

* Latest tag

* Latest

* Latest tag from $tag

* Latest

* export latest

* CR and GH

* Prepare git for chart-releaser

* Latest

* CR update

* do it by cr

* Fix version in chart.

* Update CR rags + upload release

* remove upload in case : immutable release

* Cr args : owner and repo

* Remove unused instructions

* Add git login

* remove OCI in dependancies list

* Remove Hardcode

* lower ?

* name use for tag and for CR

* Name

* Name

* Name

* Name

* Name

* Name

* looking for folder structure load for gh-pages branch

* Name

* Name .

* Ref the commit that run the workflow

* Add changelog.md as ref to release

* Update trivy action to 0.35.0 (#15)

---------

Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>
Co-authored-by: Lajus <cedric.lajus@aphp.fr>
Co-authored-by: Cédric Lajus <74196307+Superfluxx@users.noreply.github.com>

* Update CI workflow with update  (#17)

* Added support fir build-args for container-ci workflow

* Added default build-args logic, and renamed the build-args input parameter ti extra-build-args

* Added custom user-defined tags support

* Added support for ignoring hadolint rules

* Added missing git metadata step

* Modified author injection for commit vars

* Added debug step for commit author

* Added missing git fetch info

* Updated git tech depth

* Updated fetch depth

* Fixed steps order in docker image build step

* Fixed formatting issues with args

* Refactored arg parse for docker build

* Rationalized build args steps

* Added missing checkout step

* Trimmed arg-json command

* Updated args json for build-args phase

* Updated build-args logic

* Updated build-args logic

* Updated and refactored :
- Added support for Dockles Ignore
- Added support for Trivy Ignores
- Optimized workflow by removing duplicated steps qs much as possible whilst keeping parallelization
- Renamed a few steps for clarity

* Updated defaults for a few params

* Fixed weog version definition and updated parameters

* Refactored an bu,ped hadolint action version

* Added skip trivy init where it as needed

* Fixed wrong dockle parameter for scan

* Updated README

* Made artifacts refere,ce unique

* Updated docs

* Cheese dockle by running it from binary

* Clean dockle step and add argument handleling

* Fix tentative when building chart depedencies -> ignoring oci repositories

* Added fix at frst step too

* Added back missing chart dir as param

* Doc update : calling workflows

* Change release suffix condition for dev branch

* Change condition for running chart-releaser on branches

* Add release steps for feature branch in CI workflow

* add skip

* Comment on repository OCI definition

* fix CI

* Clarify release types and update workflow references

Updated README to clarify release management and workflow usage.

* update rules

* Fix config on CI Linter

* fix Yaml Linter error

* Fix Linter Errors

* Fix :

Error: ub/workflows/ci.yml:11:16: [error] too many spaces inside brackets (brackets)
Error: ub/workflows/ci.yml:11:24: [error] too few spaces after comma (commas)
Error: ub/workflows/ci.yml:11:29: [error] too many spaces inside brackets (brackets)

* add exclusion OCI helm repository

* refactoring + set path

* rebuild DEV / SNAPSHOT every time called

* fix chart release that not update index.yaml

* fix yaml lint errors

* refactor

* update version of tools used by the workflow

* add checkout

* set the version of helm (same in all steps)

* Log more info for the name of the version

* Update config for chart-Releaser

* skip upload if it is already made

* remove download

* try without upload / download at each job the chart

* Need source  for Polaris Scan

* Delete release before create it again

* skip if existe

* from main

* new line at end of file

* test option with index

* add feature branch in release process

* Choose the right package-path

* fix linter error : Error: ub/workflows/chart-ci.yml:361:1: [error] too many blank lines (1 > 0) (empty-lines)

* remove CR releaser

* downgrade chart-releaser plugin

* remove download chart

* [Temporary] Disable Helm, Checkout, Downloard pakaged Chart

* Add Chechout step

* Add Helm

* All do in 1 job

* Adjust task order in the job

* Replace chart-releaser by specifics steps.

* uncomment the right step for snapshot version name

* remove tag creation

* add login for fetch gh-pages

* Clean before MR

* add merge with helm before cr index

* update url in index.yaml

* update index with cr_releaser 1.7.0

* Fix for "chart-cr" action bug https://github.com/helm/chart-releaser-action/issues/171#issuecomment-2372464055

* same error

* Put latest tag at the right step

* again : latest_tag

* Latest tag

* Latest

* Latest tag from $tag

* Latest

* export latest

* CR and GH

* Prepare git for chart-releaser

* Latest

* CR update

* do it by cr

* Fix version in chart.

* Update CR rags + upload release

* remove upload in case : immutable release

* Cr args : owner and repo

* Remove unused instructions

* Add git login

* remove OCI in dependancies list

* Remove Hardcode

* lower ?

* name use for tag and for CR

* Name

* Name

* Name

* Name

* Name

* Name

* looking for folder structure load for gh-pages branch

* Name

* Name .

* Ref the commit that run the workflow

* Add changelog.md as ref to release

* Update trivy action to 0.35.0 (#15)

---------

Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>
Co-authored-by: Lajus <cedric.lajus@aphp.fr>
Co-authored-by: Cédric Lajus <74196307+Superfluxx@users.noreply.github.com>

* Update container-ci.yml

* Update chart-ci.yml

* Update container-ci.yml

* Update chart-ci.yml

---------

Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>
Co-authored-by: Lajus <cedric.lajus@aphp.fr>
Co-authored-by: Cédric Lajus <74196307+Superfluxx@users.noreply.github.com>

* Update versions (#21)

* Mise à jour des versions

* fix

---------

Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>
Co-authored-by: Nicolas-Delahaye <nicolas.delahaye-ext@aphp.fr>

* Update how to get polaris from github

---------

Co-authored-by: Cédric Lajus <74196307+Superfluxx@users.noreply.github.com>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@aphp.fr>
Co-authored-by: Kévin ZGRZENDEK <kevin.zgrzendek@gmail.com>